import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    nav_home: 'Home',
    nav_analysis: 'Analysis',
    nav_history: 'History',
    nav_profile: 'Profile',
    nav_signin: 'Sign In',
    nav_register: 'Register',
    nav_getstarted: 'Get Started',
    nav_signout: 'Sign Out',
    nav_darkmode: 'Dark Mode',
    nav_lightmode: 'Light Mode',

    // Footer
    footer_copy: '© 2026 SkinSense AI. Promoting Healthy Lives',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_contact: 'Contact Support',
    footer_medical: 'Medical Disclaimer',

    // Landing Page
    landing_badge: 'AI POWERED SKINCARE',
    landing_hero_title: 'Great Skin Starts With',
    landing_hero_subtitle: 'Actually Understanding Yours',
    landing_hero_desc: "Most of us have spent years buying products and hoping for the best. SkinSenseAI changes that — giving you real data about what your skin needs, so you can stop guessing and start seeing results.",
    landing_try_scanner: 'Try the scanner',
    landing_explore_tech: 'See how it works',
    landing_features_title: 'Designed for Your Journey',
    landing_features_desc: "SkinSenseAI isn't just a scanner; it's a comprehensive platform for lifelong skin health management.",
    landing_problems_title: 'Why Guessing Fails',
    landing_problems_desc: 'The skincare industry relies on trial and error. We believe your skin deserves a more rigorous, evidence-based approach.',
    landing_roadmap_title: 'Three Simple Steps',
    landing_roadmap_desc: 'Our three-step neural analysis transforms a simple smartphone capture into a data-rich dermatological assessment.',
    landing_encrypted: 'Encrypted Clinical Data',
    landing_cta_title: 'Ready for your healthiest skin ever?',
    landing_cta_desc: 'Join us and transform your skincare journey with precision data. Start your first clinical scan today.',
    landing_cta_note: 'Instant results.',
    landing_analyze_btn: 'Analyze My Skin',
    landing_team_title: 'Meet Our Team',
    landing_team_desc: 'We\'re developers who believe your skin deserves better than trial and error.',

    // Analysis text
    analysis_text1: 'Hydration',
    analysis_text2: 'UV Damage',
    analysis_text3: 'Skin Type',
    analysis_text4: 'Pores',
    analysis_text5: 'AI Confidence',
    analysis_subtext1: '85%',
    analysis_subtext2: 'Low',
    analysis_subtext3: 'Combination',
    analysis_subtext4: 'Normal',
    analysis_subtext5: '95%',

    // Features
    feat1_title: 'Skin Type Detection',
    feat1_desc: 'Snap a photo — our AI will identify your skin type and give you a clear, objective read on what you\'re actually working with.',
    feat2_title: 'Ingredient Analysis',
    feat2_desc: 'Your personal ingredient guide based on your scan results, we\'ll tell you exactly which ingredients to seek out — and which ones to steer clear of.',
    feat3_title: 'Progress Tracking',
    feat3_desc: 'Visualize your improvement over time with side-by-side heatmaps. See exactly how your barrier health and clarity are improving with your new science-backed routine.',

    // Problems
    prob1_title: 'Hidden Reactivity',
    prob1_desc: "Standard products often contain ingredients that trigger micro-inflammation invisible to the naked eye until it's too late.",
    prob2_title: 'Chemical Conflict',
    prob2_desc: 'Many "viral" skincare trends combine actives that neutralize each other or cause long-term sensitivity when used incorrectly.',
    prob3_title: 'Barrier Fatigue',
    prob3_desc: "Without precise data, it's easy to over-treat your skin, leading to chronic dehydration and premature aging.",

    // Phases
    phase1: 'STEP 01',
    phase1_title: 'Capture & Scan',
    phase1_desc: 'Use our intelligent viewfinder to secure a high-fidelity image in your environment.',
    phase2: 'STEP 02',
    phase2_title: 'Neural Diagnostics',
    phase2_desc: 'Our proprietary model scans for over 40 specific markers, from pore congestion to elasticity.',
    phase3: 'STEP 03',
    phase3_title: 'See Results',
    phase3_desc: 'Access your personalized dashboard with ingridient recommendations and a daily habit tracker.',

    // Login
    login_welcome: 'Welcome Back',
    login_subtitle: 'Access your personalized dermatological dashboard.',
    login_email: 'Email Address',
    login_password: 'Password',
    login_forgot: 'Forgot password?',
    login_remember: 'Keep me signed in for 30 days',
    login_btn: 'Sign In',
    login_or: 'Or continue with',
    login_no_account: "New to SkinSenseAI?",
    login_create: 'Create an account',
    login_loading: 'Signing in...',
    login_text1: 'Advanced AI',
    login_text2: 'Rooted in Science',

    // Register
    register_title: 'Create Account',
    register_subtitle: 'Start your personalized clinical skin journey today.',
    register_name: 'Full Name',
    register_email: 'Email Address',
    register_password: 'Password',
    register_confirm: 'Confirm Password',
    register_agree: 'I understand that my',
    register_terms: 'photo',
    register_and: 'and',
    register_privacy: 'personal data',
    register_clinical: 'will only be used for skin analysis purposes.',
    register_btn: 'Register Now',
    register_or: 'Or continue with',
    register_have_account: 'Already have an account?',
    register_signin: 'Sign in',
    register_loading: 'Registering...',
    register_text1: 'Great Skin',
    register_text2: 'Starts With',
    register_text3: 'Actually Understanding Yours.',

    // Home
    home_badge: '85% ACCURACY RATE',
    home_title1: 'Precision',
    home_title2: 'Dermatology,',
    home_subtitle: 'Powered by AI.',
    home_text1: 'SkinSense AI was born to bridge the gap between expensive dermatological consultations and the guesswork of the beauty aisle.',
    home_title3: 'Understand your skin',
    home_subtitle2: 'on a deeper level',
    home_badge2: 'DETECTION COMPLETE',
    home_text2: 'AI-guided lighting correction',
    home_text3: 'Auto-focus for macro precision',

    // Analysis
    analysis_upload: 'Upload Photo',
    analysis_camera: 'Use Camera',
    analysis_click: 'Click to upload',
    analysis_formats: 'Supported formats: JPEG, JPG, PNG, WEBP',
    analysis_change: 'Click to change photo',
    analysis_camera_allow: 'Allow Camera Access on This Site',
    analysis_camera_activate: 'ACTIVATE CAMERA',
    analysis_tips_label: 'TIPS',
    analysis_tips_text: 'For the best results, make sure your face is clearly visible with good lighting — no filters or heavy makeup.',
    analysis_btn: 'ANALYZE',
    analysis_loading: 'Analyzing your skin...',
    analysis_tips_title: 'Quick Check Skin',
    analysis_tips_subtitle: 'With Us!',
    tip1_title: 'Face',
    tip1_desc: 'Make sure your face is clearly visible and not covered by any objects',
    tip2_title: 'Lighting',
    tip2_desc: 'Use adequate lighting for a more accurate analysis result',
    tip3_title: 'Disclaimer',
    tip3_desc: 'Analysis results may vary depending on the quality of your photo',

    // History
    history_total: 'Total Scans',
    history_avg: 'Average Score',
    history_change: 'Skin Progress',
    history_no_data: 'Not enough data yet',
    history_score: 'Score',
    history_detail: 'Detail',
    history_empty: 'No scan history yet',
    history_loading: 'Loading history...',
    history_error: 'Failed to load history',

    // Profile
profile_title: 'User Profile',
profile_login_prompt: 'Please log in to view your profile',
profile_member_since: 'Member since',
profile_edit: 'EDIT',
profile_no_scan: 'No scan data yet',
profile_metric_oil: 'Oil Level',
profile_metric_moisture: 'Moisture',
profile_metric_sensitive: 'Sensitivity',
profile_metric_wrinkle: 'Wrinkles',
profile_routine_title: 'Personalized Routine',
profile_no_routine: 'Run a scan to get your personalized routine.',
profile_morning: 'Morning Protocol',
profile_evening: 'Evening Protocol',
profile_ai_insights: 'AI Insights',
profile_hydration_goal: 'Hydration Goal',
profile_no_insight: 'Run a scan to get AI recommendations.',

// Edit Profile
edit_title: 'Edit Profile',
edit_subtitle: 'Update your account information',
edit_avatar_hint: 'Click the camera icon to change photo',
edit_personal_info: 'Personal Information',
edit_name: 'Full Name',
edit_name_placeholder: 'Your full name',
edit_email: 'Email',
edit_email_placeholder: 'Email address',
edit_phone: 'Phone Number',
edit_birthdate: 'Date of Birth',
edit_skin_profile: 'Skin Profile',
edit_skin_type: 'Skin Type',
edit_skin_normal: 'Normal',
edit_skin_oily: 'Oily',
edit_skin_dry: 'Dry',
edit_skin_combo: 'Combination',
edit_skin_sensitive: 'Sensitive',
edit_skin_concerns: 'Skin Concerns',
edit_concern_acne: 'Acne',
edit_concern_pores: 'Pores',
edit_concern_darkspot: 'Dark Spots',
edit_concern_wrinkle: 'Wrinkles',
edit_concern_dull: 'Dull Skin',
edit_concern_darkcircle: 'Dark Circles',
edit_concern_excess_oil: 'Excess Oil',
edit_concern_dry_skin: 'Dry Skin',
edit_cancel: 'Cancel',
edit_save: 'Save Changes',
edit_saving: 'Saving...',
edit_saved: 'Saved!',
  },

  id: {
    // Navbar
    nav_home: 'Beranda',
    nav_analysis: 'Analisis',
    nav_history: 'Riwayat',
    nav_profile: 'Profil',
    nav_signin: 'Masuk',
    nav_register: 'Daftar',
    nav_getstarted: 'Mulai',
    nav_signout: 'Keluar',
    nav_darkmode: 'Mode Gelap',
    nav_lightmode: 'Mode Terang',

    // Footer
    footer_copy: '© 2026 SkinSense AI. Mempromosikan Hidup Sehat',
    footer_privacy: 'Kebijakan Privasi',
    footer_terms: 'Syarat Layanan',
    footer_contact: 'Hubungi Dukungan',
    footer_medical: 'Disclaimer Medis',

    // Landing Page
    landing_badge: 'AI UNTUK PERAWATAN KULITMU',
    landing_hero_title: 'Kulit Sehat Dimulai dari',
    landing_hero_subtitle: 'Mengenali Kulitmu Sendiri',
    landing_hero_desc: 'Selama ini kita beli produk dan berharap hasilnya bagus. SkinSenseAI mengubah itu — memberimu data nyata tentang apa yang dibutuhkan kulitmu, supaya kamu bisa berhenti menebak-nebak dan mulai melihat hasilnya.',
    landing_try_scanner: 'Coba scanner',
    landing_explore_tech: 'Lihat cara kerjanya',
    landing_features_title: 'Dirancang untuk Menemanimu',
    landing_features_desc: 'SkinSense AI bukan sekadar scanner; ini adalah platform lengkap untuk menjaga kesehatan kulitmu jangka panjang.',
    landing_problems_title: 'Mengapa Menebak Itu Gagal',
    landing_problems_desc: 'Industri skincare bergantung pada coba-coba. Kami percaya kulit Anda layak mendapat pendekatan yang lebih ketat dan berbasis bukti.',
    landing_roadmap_title: 'Peta Jalan Klinis Anda',
    landing_roadmap_desc: 'Analisis neural tiga langkah kami mengubah foto smartphone sederhana menjadi penilaian dermatologis yang kaya data.',
    landing_encrypted: 'Data Klinis Terenkripsi',
    landing_cta_title: 'Siap untuk kulit paling sehat Anda?',
    landing_cta_desc: 'Bergabunglah bersama kami dan mulai perjalanan perawatan kulitmu dengan data yang nyata. Mulai scan pertamamu hari ini.',
    landing_cta_note: 'Hasil instan.',
    landing_analyze_btn: 'Analisis Kulit Saya',
    landing_team_title: 'Kenali Tim Kami',
    landing_team_desc: 'Kami adalah para pengembang yang percaya kulitmu layak mendapatkan sesuatu yang lebih baik daripada sekadar coba-coba.',

    // Analysis text
    analysis_text1: 'Hidrasi',
    analysis_text2: 'Kerusakan UV',
    analysis_text3: 'Tipe Skin',
    analysis_text4: 'Pori-pori',
    analysis_text5: 'Keberhasilan AI',
    analysis_subtext1: '85%',
    analysis_subtext2: 'Rendah',
    analysis_subtext3: 'Kombinasi',
    analysis_subtext4: 'Normal',
    analysis_subtext5: '95%',

    // Features
    feat1_title: 'Deteksi Jenis Kulit',
    feat1_desc: 'Ambil foto — AI kami akan mengidentifikasi tipe kulitmu dan memberimu gambaran yang jelas tentang kondisi kulitmu saat ini.',
    feat2_title: 'Analisis Bahan',
    feat2_desc: 'Berdasarkan hasil scan-mu, kami akan memberi tahu bahan apa yang cocok untuk kulitmu — dan mana yang sebaiknya dihindari.',
    feat3_title: 'Lacak Perkembangan',
    feat3_desc: 'Lihat perubahan kulitmu dari waktu ke waktu dengan perbandingan visual yang jelas. Tahu persis apakah rutinmu benar-benar bekerja.',

    // Problems
    prob1_title: 'Reaktivitas Tersembunyi',
    prob1_desc: 'Produk standar sering mengandung bahan yang memicu peradangan mikro yang tidak terlihat mata hingga terlambat.',
    prob2_title: 'Konflik Bahan Kimia',
    prob2_desc: 'Banyak tren skincare "viral" menggabungkan bahan aktif yang saling menetralkan atau menyebabkan sensitivitas jangka panjang.',
    prob3_title: 'Kelelahan Barrier',
    prob3_desc: 'Tanpa data yang tepat, mudah terjadi over-treatment kulit yang menyebabkan dehidrasi kronis dan penuaan dini.',

    // Phases
    phase1: 'STEP 01',
    phase1_title: 'Ambil & Pindai',
    phase1_desc: 'Gunakan viewfinder cerdas kami untuk mendapatkan gambar berkualitas tinggi di lingkungan Anda.',
    phase2: 'STEP 02',
    phase2_title: 'Diagnostik Neural',
    phase2_desc: 'Model kami memindai lebih dari 40 penanda spesifik, dari kemacetan pori hingga elastisitas.',
    phase3: 'STEP 03',
    phase3_title: 'Lihat Hasil',
    phase3_desc: 'Akses dashboard personal Anda dengan formulasi yang direkomendasikan dan pelacak kebiasaan harian.',

    // Login
    login_welcome: 'Selamat Datang Kembali',
    login_subtitle: 'Akses dashboard dermatologi personal Anda.',
    login_email: 'Alamat Email',
    login_password: 'Kata Sandi',
    login_forgot: 'Lupa kata sandi?',
    login_remember: 'Tetap masuk selama 30 hari',
    login_btn: 'Masuk',
    login_or: 'Atau lanjutkan dengan',
    login_no_account: 'Baru di SkinSenseAI?',
    login_create: 'Buat akun',
    login_loading: 'Sedang masuk...',
    login_text1: 'AI Canggih',
    login_text2: 'Berbasis Pengetahuan',

    // Register
    register_title: 'Buat Akun',
    register_subtitle: 'Mulai perjalanan kulit klinis personal Anda hari ini.',
    register_name: 'Nama Lengkap',
    register_email: 'Alamat Email',
    register_password: 'Kata Sandi',
    register_confirm: 'Konfirmasi Kata Sandi',
    register_agree: 'Saya setuju bahwa',
    register_terms: 'foto',
    register_and: 'dan',
    register_privacy: 'data saya',
    register_clinical: 'hanya digunakan untuk keperluan analisis kulit.',
    register_btn: 'Daftar Sekarang',
    register_or: 'Atau lanjutkan dengan',
    register_have_account: 'Sudah punya akun?',
    register_signin: 'Masuk',
    register_loading: 'Mendaftarkan...',
    register_text1: 'Skin yang Sehat',
    register_text2: 'Dimulai dari',
    register_text3: 'Pemahaman yang Tepat.',

    // Home
    home_badge: 'TINGKAT AKURASI 85%',
    home_title1: 'Dermatologi',
    home_title2: 'Presisi,',
    home_subtitle: 'Didukung AI',
    home_text1: 'SkinSense AI lahir untuk menjembatani kesenjangan antara konsultasi dermatologi yang mahal dan ketidakpastian saat memilih produk kecantikan.',
    home_title3: 'Kenali kulit Anda',
    home_subtitle2: 'lebih dalam',
    home_badge2: 'DETEKSI SELESAI',
    home_text2: 'Koreksi pencahayaan dengan panduan AI',
    home_text3: 'Auto-fokus untuk presisi detail',

    // Analysis
    analysis_upload: 'Upload Foto',
    analysis_camera: 'Gunakan Kamera',
    analysis_click: 'Klik untuk upload',
    analysis_formats: 'Format didukung: JPEG, JPG, PNG, WEBP',
    analysis_change: 'Klik untuk ganti foto',
    analysis_camera_allow: 'Izinkan Akses Kamera pada Situs ini',
    analysis_camera_activate: 'AKTIFKAN KAMERA',
    analysis_tips_label: 'TIPS',
    analysis_tips_text: 'Untuk mendapatkan hasil analisis yang optimal, pastikan wajah terlihat jelas dengan pencahayaan yang baik serta tanpa penggunaan filter atau makeup berlebih.',
    analysis_btn: 'ANALISIS',
    analysis_loading: 'Menganalisis Kulit...',
    analysis_tips_title: 'Cek Kulit Cepat',
    analysis_tips_subtitle: 'Bersama Kami!',
    tip1_title: 'Wajah',
    tip1_desc: 'Pastikan wajah Anda terlihat jelas tanpa tertutup objek apapun',
    tip2_title: 'Cahaya',
    tip2_desc: 'Gunakan pencahayaan yang cukup agar hasil analisis lebih akurat',
    tip3_title: 'Disclaimer',
    tip3_desc: 'Hasil analisis yang Anda dapatkan bisa berbeda tergantung kualitas foto',

    // History
    history_total: 'Total Scan',
    history_avg: 'Skor Rata-Rata',
    history_change: 'Perubahan Kulit',
    history_no_data: 'Belum cukup data',
    history_score: 'Skor',
    history_detail: 'Detail',
    history_empty: 'Belum ada riwayat deteksi',
    history_loading: 'Memuat riwayat...',
    history_error: 'Gagal memuat riwayat',

    // Profile
profile_title: 'Profil Pengguna',
profile_login_prompt: 'Silakan login untuk melihat profil',
profile_member_since: 'Member sejak',
profile_edit: 'EDIT',
profile_no_scan: 'Belum ada data scan',
profile_metric_oil: 'Kadar Minyak',
profile_metric_moisture: 'Kelembapan',
profile_metric_sensitive: 'Sensitif',
profile_metric_wrinkle: 'Kerutan',
profile_routine_title: 'Rutinitas Personal',
profile_no_routine: 'Lakukan scan untuk mendapatkan rekomendasi rutinitas.',
profile_morning: 'Protokol Pagi',
profile_evening: 'Protokol Malam',
profile_ai_insights: 'Wawasan AI',
profile_hydration_goal: 'Target Hidrasi',
profile_no_insight: 'Lakukan scan untuk mendapatkan rekomendasi AI.',

// Edit Profile
edit_title: 'Edit Profil',
edit_subtitle: 'Perbarui informasi akun Anda',
edit_avatar_hint: 'Klik ikon kamera untuk ganti foto',
edit_personal_info: 'Informasi Pribadi',
edit_name: 'Nama Lengkap',
edit_name_placeholder: 'Nama lengkap',
edit_email: 'Email',
edit_email_placeholder: 'Alamat email',
edit_phone: 'Nomor Telepon',
edit_birthdate: 'Tanggal Lahir',
edit_skin_profile: 'Profil Kulit',
edit_skin_type: 'Tipe Kulit',
edit_skin_normal: 'Normal',
edit_skin_oily: 'Berminyak',
edit_skin_dry: 'Kering',
edit_skin_combo: 'Kombinasi',
edit_skin_sensitive: 'Sensitif',
edit_skin_concerns: 'Masalah Kulit',
edit_concern_acne: 'Jerawat',
edit_concern_pores: 'Pori-Pori',
edit_concern_darkspot: 'Flek Hitam',
edit_concern_wrinkle: 'Kerutan',
edit_concern_dull: 'Kulit Kusam',
edit_concern_darkcircle: 'Lingkaran Hitam',
edit_concern_excess_oil: 'Minyak Berlebih',
edit_concern_dry_skin: 'Kulit Kering',
edit_cancel: 'Batal',
edit_save: 'Simpan Perubahan',
edit_saving: 'Menyimpan...',
edit_saved: 'Tersimpan!',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
